### ISSUE TITLE
function completes before deleting anything

### ISSUE THREAD

**Issue by sns-sem** [shinnn/rmfr#2]
const rmfr = require('rmfr');

```
(async () => {
  console.log('start');
  await rmfr('my/path/here');
  console.log('end');
})();
```

When running this code, both 'start' and 'end' go off at the same time before anything in deleted. Am I misunderstanding how this is supposed to work?

I would like to wait until the folder is completely deleted before the promise is fulfilled.

**Comment by shinnn** [comment]
I cannot reproduce it.

Replace `console.log('end')` with `console.log(require('fs').existsSync('my/path/here')`.

**Comment by shinnn** [comment]
No feedback.
